---

- name: Get Plugins
  get_url: 
    url: "{{ pluginsurl }}" 
    dest: "{{ download_dir }}/{{ pluginssrc }}.tar.gz"
    validate_certs: no

- name: Unpack Plugin source files
  shell: cd {{ download_dir }} && tar -xzvf {{ pluginssrc }}.tar.gz creates={{ download_dir }}/{{ pluginssrc }}

- name: Configure Plugins
  shell: cd {{ download_dir }}/{{ pluginssrc }} && ./tools/setup && ./configure creates={{ download_dir }}/{{ pluginssrc }}/Makefile

- name: Make Plugins
  shell: cd {{ download_dir }}/{{ pluginssrc }} && make creates={{ download_dir }}/{{ pluginssrc }}/plugins/check_ping

- name: Make Install Plugins
  become: yes
  shell: cd {{ download_dir }}/{{ pluginssrc }} && make install creates=/usr/local/nagios/libexec/check_ping
