---
- name: Update apt cache
  become: yes
  apt: update_cache=yes
  changed_when: False

- name: install apache
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
   - autoconf 
   - gcc 
   - libc6 
   - libmcrypt-dev
   - make 
   - libssl-dev
   - wget 
   - bc
   - gawk
   - dc
   - build-essential
   - snmp
   - libnet-snmp-perl
   - gettext
   - unzip 
   - apache2 
   - apache2-utils 
   - php5
   - libgd2-xpm-dev
   - python-passlib
